import type { Metadata } from "next";
import Menu from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "RedMascotas",
  description: "Generated by create next app",
};
export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`min-h-screen flex flex-col`}>
      <Menu />
      <main className="flex-1">{children}</main>
      <Footer />
    </div>
  );
}
